name: tensorflow-gpu-tutorials

dependencies:
  - python=3.6.*
  - matplotlib=3.0.*
  - jupyterlab
  - pandas=0.24.*
  - pillow=6.0.*
  - pip=19.0.*
  - scikit-learn=0.20.*
  - tensorflow-gpu=1.13.*
  - py-xgboost-gpu=0.80.*
  - pip:
    - kaggle==1.5.*
