name: null

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - pillow=6.0
  - h5py=2.9
  - jupyterlab=0.35
  - kaggle=1.5
  - cudatoolkit=10.0
  - cudnn=7.6
  - tensorflow-gpu=1.13
